// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvk13JihZaX3F9nRmGlTvtK-Wymq3A4M',
    appId: '1:585904970458:web:5127d8a20d7ee6108123e3',
    messagingSenderId: '585904970458',
    projectId: 'app-fluter-4d733',
    authDomain: 'app-fluter-4d733.firebaseapp.com',
    databaseURL: 'https://app-fluter-4d733-default-rtdb.firebaseio.com',
    storageBucket: 'app-fluter-4d733.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGqUMv9mxr6GGlHFQkUtb0K48Nk8Bpw0',
    appId: '1:585904970458:android:f20015839581b5aa8123e3',
    messagingSenderId: '585904970458',
    projectId: 'app-fluter-4d733',
    databaseURL: 'https://app-fluter-4d733-default-rtdb.firebaseio.com',
    storageBucket: 'app-fluter-4d733.firebasestorage.app',
  );

}